### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#1]
PostCSS is often packaged to JS bundle. We need `index.browser.js` version. It is OK just to return string there (but you will need to convert `undefined` and numbers to strings to be compatible with types).

Here a way to use them in `package.json`: https://github.com/ai/nanocolors/blob/main/package.json#L20-L23 https://github.com/ai/nanocolors/blob/main/package.json#L28

**Comment by alexeyraspopov** [comment]
`picocolors@0.1.0` is now published and supports `browser` field
https://github.com/alexeyraspopov/picocolors/releases/tag/v0.1.0
