### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#11]
What do you think if tests will print it’s value to terminal to check the result by eyes?

```js
let str = …
console.log(str)
asset.equal(str, ideal)
```

It is just idea, tests are good even without it.

**Comment by alexeyraspopov** [comment]
I've added this just recently in https://github.com/alexeyraspopov/picocolors/commit/52816157572c334dab36d780915f4ae68889b5f6 and you can find the output in latest job runs https://github.com/alexeyraspopov/picocolors/runs/3723455469

**Comment by ai** [comment]
Looks nice.
