### ISSUE TITLE
How do you measure speed?

### ISSUE THREAD

**Issue by danBamikiya** [alexeyraspopov/picocolors#12]
Hey y'all! Nice work here!

How do you measure the speed?

**Comment by ai** [comment]
You can use benchmarks from [here](https://github.com/ai/nanocolors/tree/main/test): `./simple-benchmark.js`, `./complex-benchmark.js`, `./loading.cjs`, and `./size.js`

**Comment by danBamikiya** [comment]
Thanks a lot!
