### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#16]
ChangeLog is very important for utility package. When developer will see `picocolors` updates in `yarn upgrade-interactive` (especially major update), they will need a quick and simple way to find differences and update safety.

**Comment by alexeyraspopov** [comment]
`CHANGELOG.md` has been added in https://github.com/alexeyraspopov/picocolors/commit/7e22ad1ee90845d82a3b99cc1cd9e4ff2fa9aefd
