### ISSUE TITLE
Colorette benchmark results are outdated

### ISSUE THREAD

**Issue by kibertoad** [alexeyraspopov/picocolors#38]
Hi! We've made some performance optimizations lately, so I believe that numbers as listed currently in readme are no longer accurate. Would you consider recalculating them with the latest version of Colorette?

Also it would probably be helpful to list versions for all the libraries mentioned in the benchmark for fairness.

**Comment by alexeyraspopov** [comment]
Just pushed https://github.com/alexeyraspopov/picocolors/commit/0836f3c59c5ce814c62dec7aa4301505092700ef with the updated numbers I got from the most recent benchmarks job run.
