### ISSUE TITLE
Add API to manually change color mode

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#4]
PostCSS, Logux Server and some other Nano Colors users have own options to change colors.

Can we have a way to manually change support mode like:

```js
import { createColor } from 'picocolors'

let { red } = createColor(options.color)
```

Or:

```js
import { setColors, isColorSupported } from 'picocolors'

setColors(options.color ?? isColorSupported)
```

**Comment by alexeyraspopov** [comment]
In #22 I've implemented a similar to `nanocolors` and `colorette` approach, though some input needed since I'm not entirely convinced about the proper use case for this feature. Once review is done, we can definitely ship another version.
