### ISSUE TITLE
Colors are always enabled in CI, even when output is piped

### ISSUE THREAD

**Issue by anko** [alexeyraspopov/picocolors#41]
I wrote a program that uses this module. The tests pass on my local machine (because the colours are sensibly disabled when the program's output is piped), but they fail in CI, because [this line](https://github.com/alexeyraspopov/picocolors/blob/6b43e8e83bcfe69ad1391a2bb07239bf11a13bc4/picocolors.js#L9) turns colours on _no matter what_ if `process.env.CI` is set. Even if it's not in a TTY.

When stdout is not a TTY, I think colour should always be disabled, unless it's specifically forced on with `FORCE_COLOR`.

**Comment by ai** [comment]
Just for the context. GitHub Actions has broken TTY detection. CI supports colors, but report lack of TTY.

But I am not sure about the best solution here.

**Comment by anko** [comment]
I see now. [Upstream issue is here](https://github.com/actions/runner/issues/241).  I'd like to have color on a test script on GH Actions too, I just don't want color on every child process that it starts and internally reads the output of.

```sh
$ node -e "console.log(require('picocolors').isColorSupported)" | cat
false
$ CI=1 node -e "console.log(require('picocolors').isColorSupported)" | cat
true
```

Other CI services that also set `$CI` might not even support colours, but they'd be enabled anyway and the tests would fail. It would be really confusing trying to understand what's going on, because the CI might just show something like `"OK" is not equal to "OK"`.

I think we should either;

- Leave users to work around their chosen CI system's bugs themselves, instead of forcing them to work around our workaround of a bug in a specific CI system that they might not even be using, or
- Find some way to cheaply but reliably detect Github Actions, so we can turn colours on for it without relying solely on the `$CI` variable.

**Comment by anko** [comment]
> Find some way to cheaply but reliably detect Github Actions

Oh. [`$GITHUB_ACTIONS` is always set to `true` on Github Actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables). :tada:

**Comment by anko** [comment]
I worked around this by using [`supports-color`](https://github.com/chalk/supports-color), which is smallish at 10kB unpacked, 0 deps, and detects colour support correctly in a whole lot of environments including silly ones [like GH Actions](https://github.com/chalk/supports-color/blob/4f459ee311817cfad1332731a2c1060e07b2015e/index.js#L108).

**Comment by erezrokah** [comment]
We're experiencing this too, see https://github.com/netlify/cli/pull/4354#issuecomment-1057057230 in case a reproduction is needed.
