### ISSUE TITLE
Yoctocolors

### ISSUE THREAD

**Issue by dy** [alexeyraspopov/picocolors#46]
Missing benchmark for https://github.com/sindresorhus/yoctocolors

**Comment by alexeyraspopov** [comment]
I don't think the author is going to support this library as something that is not just a joke, so I don't see a reason to include it in the benchmark. Also, yoctocolors is ESM only, something we need to fix in #45 first.

**Comment by dy** [comment]
Curious what makes you think that's a joke? Doesn't seem funny if something claims to be faster, does it?
