### ISSUE TITLE
Can't use named ESM imports

### ISSUE THREAD

**Issue by SuperchupuDev** [alexeyraspopov/picocolors#48]
Using a named import doesn't work at all, only default imports

```js
import { bold, yellow, blue, red } from 'picocolors';
// SyntaxError: The requested module 'picocolors' does not provide an export named 'blue'

import picocolors from 'picocolors';
picocolors.blue // all fine
```
I'm using node v18.4.0

**Comment by alexeyraspopov** [comment]
For the sake of broader compatibility (Node.js 6+) and optimized package size, picocolors only provides the default export (since it's implemented as CJS module). `import colors from "picocolors";` should be sufficient.

We may revisit this in the future at some point, if it has concrete benefits.

**Comment by SuperchupuDev** [comment]
@alexeyraspopov thinking about this again, I think it can be possible to support named imports if the `createColors()` function is removed, since ESM named exports from CJS code only work if they are explicitly defined in `module.exports`. Would a PR making this change get accepted if it doesn't drastically change filesize?

**Comment by uiolee** [comment]
Also looking forward to esm

**Comment by SuperchupuDev** [comment]
for esm i ended up switching to yoctocolors

**Comment by alexeyraspopov** [comment]
I should've elaborated more on this. Let me get things straight.

### Picocolors is ESM compatible

**You can import and use picocolors from ES Module without any additional tricks or configuration.** Simply `import colors from "picocolors";` and you're good to go. 

### There are no special benefit from having named exports for each color

It is just a matter of taste. `import colors from "picocolors";` or `import {red, green, blue, dim} from "picocolors";`. Does it really makes do-or-die difference in your work? The answer is no.

This library may or may not introduce named exports if there's gonna be any benefit (for speed or size) out of it. The library is the smallest Node.js script that does not need to be tree-shakeable. You don't use it so very often to claim that default export somehow slows you down. There isn't even an argument here.

> for esm i ended up switching to yoctocolors

@SuperchupuDev, feel free to use any library you want. Even if it has bugs like yoctocolors does:

<img width="555" alt="image" src="https://github.com/alexeyraspopov/picocolors/assets/858295/84155c94-28ac-4ede-a244-ea25800cd1ff">
