### ISSUE TITLE
Why do you use let and not const?

### ISSUE THREAD

**Issue by MrFoxPro** [alexeyraspopov/picocolors#57]

**Comment by alexeyraspopov** [comment]
1. `let` is shorter than `const` which means smaller package without loosing any capabilities. It could've been `var`, I wouldn't care.
2. In my projects I don't use `const` as default way of declaring a variable. `const` by default is a bad practice that should've never been adopted.

**Comment by mrazauskas** [comment]
> 2. In my projects I don't use `const` as default way of declaring a variable. `const` by default is a bad practice that should've never been adopted.

@alexeyraspopov Can I ask why? (No bike-shedding here. Pure curiosity. I agree that `let` means smaller package size, only wondering why `const` is a bad practice?)
