### ISSUE TITLE
Add Node.js 6 to CI

### ISSUE THREAD

**Issue by ai** [alexeyraspopov/picocolors#6]
Don’t want to scary you, but current Babel need Node.js 6 support.

Browserslist need very old Node.js as well because we can’t do major releases often to clean old Node.js versions.

**Comment by alexeyraspopov** [comment]
As a part of #8 I added Node.js v6 to the testing matrix. v6-10 only running CJS tests as we don't expect them to be using anything else.

**Comment by alexeyraspopov** [comment]
`picocolors@0.1.0` is now published and supports Node.js v6
https://github.com/alexeyraspopov/picocolors/releases/tag/v0.1.0
