### ISSUE TITLE
Align `FORCE_COLOR=0` with Node.js meaning

### ISSUE THREAD

**Issue by nicolo-ribaudo** [alexeyraspopov/picocolors#62]
Node.js allows disabling color by passing `FORCE_COLOR=0` (https://nodejs.org/api/tty.html#writestreamgetcolordepthenv). Would you be open to a PR checking if `FORCE_COLOR` is 0?

For context, we just migrated Babel from Chalk to picocolors and found this difference. For now we are going to roll our own color detection logic to preserve the Node.js-like behavior.

**Comment by alexeyraspopov** [comment]
I'm considering switch to https://nodejs.org/api/tty.html#writestreamhascolorscount-env that seems to be available since Node.js v10.16. I will try to find some tests to see how it works with FORCE_COLOR variable and will make sure too keep this behavior in mind. There's probably a small patch I can make in the meantime for v1 to avoid breaking changes.

**Comment by nicolo-ribaudo** [comment]
<img width="683" alt="image" src="https://github.com/alexeyraspopov/picocolors/assets/7000710/0f5827fd-f9b5-4b81-ae22-cd769305bce3">

For what is worth, I tried running a totally unscientific poll on Twitter and it seems like people are split on the behavior of `FORCE_COLOR=0`. While I still think that it's good for Node.js libraries to align with Node.js, changing what `FORCE_COLOR=0` does should probably be considered a breaking change.

**Comment by alexeyraspopov** [comment]
> because NO_COLOR= node ... will trigger that condition, but still be a "" value.

Good point, that's something worth fixing. Not quite sure how one would end up in situation like `NO_COLOR= node` 😅 .

**Comment by alexeyten** [comment]
> Not quite sure how one would end up in situation like `NO_COLOR= node`

Easy. That would be one of the thing I would try to override `NO_COLOR` that was set somewhere before this line.
For example
```bash
export NO_COLOR=1
node aaa
node bbb
# I want only this command to use colors (and my expectation failed)
NO_COLOR= node ccc
node ddd
...
```

**Comment by alexeyraspopov** [comment]
Alright, I finally got a moment to fix this: https://github.com/alexeyraspopov/picocolors/pull/87. Should also cover the issue with dynamic `require()` calls once and for all.

**Comment by alexeyraspopov** [comment]
Version `1.1.1` is published.

**Comment by nicolo-ribaudo** [comment]
@alexeyraspopov Hey, I was trying to update to the version of `picocolors` that includes #87 but it seems like this issue has not been fixed.

In Node.js `FORCE_COLOR=0` means "disable colors" (https://nodejs.org/api/tty.html#writestreamgetcolordepthenv), while in `picocolors` it means "enable colors" because `!!"0"` is true (first check at https://github.com/alexeyraspopov/picocolors/blob/0e7c4af2de299dd7bc5916f2bddd151fa2f66740/picocolors.js#L4).
