### ISSUE TITLE
Can't get the picocolors@^1.0.1

### ISSUE THREAD

**Issue by walidmokhtari** [alexeyraspopov/picocolors#66]
Actually, I tried to get the Picocolors version 1.0.1, but I encountered this error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for picocolors@^1.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /home/wmo/.npm/_logs/2024-05-15T19_40_10_978Z-debug-0.log

**Comment by alexeyten** [comment]
Have you checked /home/wmo/.npm/_logs/2024-05-15T19_40_10_978Z-debug-0.log

Package is clearly published and that's definitely not a problem with package itself, but with registry you're using.

**Comment by walidmokhtari** [comment]
The problem is fixed after clearing the npm cache,  sorry for the inconvenience thank you for your answer, i will close this issue.
