### ISSUE TITLE
API Extractor fails to extract types

### ISSUE THREAD

**Issue by ishon19** [alexeyraspopov/picocolors#77]
Hello! I was working on a feature to replace `chalk` with `picocolors` in `jest` repo, however the build process just fails since the [`@microsoft/api-extractor`](https://www.npmjs.com/package/@microsoft/api-extractor) used in the project is not happy about the `types.ts` file in the exported `picocolors` npm package, as shown in the screenshot below:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/b038c3c2-942a-40a4-b92a-61119f22677f">

Linking the PR as well for more context: https://github.com/jestjs/jest/pull/15197

But when I manually go to the `node_modules/picocolors` and change the file name from `types.ts` to `types.d.ts`, it just works fine. Just wanted to know, is there any possible workaround? And if this seems to be a potential fix, I'm happy to contribute. Any help/suggestion appreciated! :)

**Comment by ishon19** [comment]
Thanks a lot guys!

**Comment by alexeyraspopov** [comment]
I'll try to push new version this week, there's some pending changes I should've pushed a while ago. Thanks for your patience 🙏🏻

**Comment by alexeyraspopov** [comment]
`v1.1.1` is now published.
