### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by benmccann** [alexeyraspopov/picocolors#78]
Hi, I wanted to ask for a new version. I'd like to use https://github.com/alexeyraspopov/picocolors/pull/55, which was committed a couple of months ago and not released yet.

Thanks!

**Comment by Jayllyz** [comment]
Would be nice if it could be published with provenance too.

See https://docs.npmjs.com/generating-provenance-statements

**Comment by alexeyraspopov** [comment]
I'm planning the release this week. I'm short on time but will do my best to wrap it up and update related tickets. @Jayllyz thanks for the link, I'll see if anything can work for picocolors here.

**Comment by 43081j** [comment]
Also do let us know if there are any other open issues or PRs you need help with to get the release out

The community is pretty invested through e18e etc so I'm sure there's many happy to help

**Comment by benmccann** [comment]
So that I don't lose track of them: the `changesets` (https://github.com/changesets/changesets/pull/1417) and `json-schema-to-typescript` libraries are both waiting for this change

**Comment by alexeyraspopov** [comment]
Version 1.1.0 with bright color variants has now been published. Thanks everyone for patience.

**Comment by benmccann** [comment]
thank you so much!!
