### ISSUE TITLE
Why `'CI' in env` forces color support?

### ISSUE THREAD

**Issue by alexeyten** [alexeyraspopov/picocolors#79]
https://github.com/alexeyraspopov/picocolors/blob/main/picocolors.js#L9

I'm confused why setting `CI` env (with literally any value) should mean that there is color support?

**Comment by ai** [comment]
Because `isTTY` is broken on GitHub Actions

**Comment by alexeyten** [comment]
OK, thank you.

**Comment by JounQin** [comment]
This breaks CI snapshot test...
