### ISSUE TITLE
BUG - When bundled in ES module, cannot run on platforms other than win32

### ISSUE THREAD

**Issue by vincesp** [alexeyraspopov/picocolors#83]
When bundled into an ES Module using rollup, the resulting code does not run on any platform other than win32. The following line yields an error:

https://github.com/alexeyraspopov/picocolors/blob/4e946891bb511accf089f4d52003afbcbc1bb928/picocolors.js#L8

Error:
```
                (require != null && require$$0$h.isatty(1) && env.TERM !== "dumb") ||
                 ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '.../package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

This expression is not evaluated on win32 as the previous line yields `true` then.

Node.js v20.17.0
picocolors v1.1.0

picocolors v1.0.0 is not affected by this bug.

**Comment by alexeyten** [comment]
duplicate #67
